-- Entry point for Statusline (bitty-terminal.statusline).
--
-- The host evaluates this file once per plugin activation and owns every
-- resource created here for the lifetime of that generation.
--
-- The `bitty` namespace below is the accepted Plugin API v1 surface sketch
-- from bitty-docs `docs/specifications/plugin-platform-rfc.md` (OQ-011).
-- Concrete argument shapes and the authoritative bindings are generated by
-- the SDK (`bitty.d.lua`, R-SDK-1); re-check this file against that contract
-- when it lands and do not use surface the contract does not define.
--
-- Capabilities used here must match `bitty-plugin.toml`: the notification
-- below is covered by the single `platform.notify` request. No other ambient
-- authority (filesystem, process, network, clipboard, terminal input) is
-- granted or assumed.

local M = {}

-- Commands are qualified by plugin id; duplicate qualified names are rejected
-- at graph construction time instead of shadowing another plugin.
bitty.commands.register({
  name = "bitty-terminal.statusline:hello",
  description = "Print a greeting from Statusline.",
  run = function()
    bitty.notify.show({
      title = "Statusline",
      body = "Hello from bitty-terminal.statusline.",
    })
  end,
})

return M
